# Generated by Django 6.1 on 2026-08-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirthRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_full_name_amharic', models.CharField(max_length=255, verbose_name='የህፃኑ ሙሉ ስም')),
                ('child_full_name_english', models.CharField(max_length=255, verbose_name='Child Full Name')),
                ('sex', models.CharField(choices=[('M', 'Male / ወንድ'), ('F', 'Female / ሴት')], max_length=1)),
                ('birth_day', models.IntegerField()),
                ('birth_month', models.IntegerField()),
                ('birth_year_ec', models.IntegerField(verbose_name='የትውልድ ዓ.ም (E.C.)')),
                ('birth_year_gc', models.IntegerField(verbose_name='Year (G.C.)')),
                ('nationality', models.CharField(default='Ethiopian / ኢትዮጵያዊ', max_length=100)),
                ('subcity', models.CharField(max_length=100, verbose_name='ክፍለ ከተማ / Subcity')),
                ('woreda', models.CharField(max_length=50, verbose_name='ወረዳ / Woreda')),
                ('hospital_org_name', models.CharField(max_length=255, verbose_name='የተወለዱበት ተቋም / Hospital Name')),
                ('father_name_amharic', models.CharField(max_length=255, verbose_name='የአባት ሙሉ ስም')),
                ('father_name_english', models.CharField(max_length=255, verbose_name='Father Full Name')),
                ('mother_name_amharic', models.CharField(max_length=255, verbose_name='የእናት ሙሉ ስም')),
                ('mother_name_english', models.CharField(max_length=255, verbose_name='Mother Full Name')),
                ('applicant_name_amharic', models.CharField(max_length=255, verbose_name='አመልካች ሙሉ ስም')),
                ('applicant_relation', models.CharField(max_length=100, verbose_name='ዝምድና / Relation')),
                ('hospital_document', models.FileField(upload_to='birth_documents/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review / በመጠባበቅ ላይ'), ('APPROVED', 'Approved / ጸድቋል'), ('REJECTED', 'Rejected / ተቀባይነት አላገኘም')], default='PENDING', max_length=10)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
