# Generated by Django 6.1 on 2026-08-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthregistration',
            name='child_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/children/', verbose_name='የህፃኑ ፎቶ / Child Photo'),
        ),
        migrations.AddField(
            model_name='birthregistration',
            name='father_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/fathers/', verbose_name='የአባት ፎቶ / Father Photo'),
        ),
        migrations.AddField(
            model_name='birthregistration',
            name='mother_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/mothers/', verbose_name='የእናት ፎቶ / Mother Photo'),
        ),
    ]
