# Generated by Django 6.1 on 2026-08-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_birthregistration_child_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthregistration',
            name='child_photo',
            field=models.ImageField(blank=True, default='', upload_to='photos/children/', verbose_name='የህፃኑ ፎቶ / Child Photo'),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='father_photo',
            field=models.ImageField(blank=True, default='', upload_to='photos/fathers/', verbose_name='የአባት ፎቶ / Father Photo'),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='hospital_document',
            field=models.FileField(blank=True, default='', upload_to='birth_documents/'),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='mother_photo',
            field=models.ImageField(blank=True, default='', upload_to='photos/mothers/', verbose_name='የእናት ፎቶ / Mother Photo'),
        ),
    ]
