# Generated by Django 6.1 on 2026-08-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_birthregistration_child_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthregistration',
            name='appointment_date',
        ),
        migrations.RemoveField(
            model_name='birthregistration',
            name='nationality',
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='applicant_name_amharic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='applicant_relation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='birth_year_ec',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='birth_year_gc',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='child_full_name_amharic',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='child_full_name_english',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='child_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/children/'),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='father_name_amharic',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='father_name_english',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='father_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/fathers/'),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='hospital_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/hospitals/'),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='hospital_org_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='mother_name_amharic',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='mother_name_english',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='mother_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/mothers/'),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='sex',
            field=models.CharField(choices=[('MALE', 'Male / ወንድ'), ('FEMALE', 'Female / ሴት')], max_length=10),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending / ተጠባባቂ'), ('APPROVED', 'Approved / የፀደቀ'), ('REJECTED', 'Rejected / የተከለከለ')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='subcity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='woreda',
            field=models.CharField(max_length=50),
        ),
    ]
