# Generated by Django 6.1 on 2026-08-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_birthregistration_appointment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthregistration',
            name='applicant_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='birthregistration',
            name='applicant_name_english',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='birthregistration',
            name='applicant_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
