# Generated by Django 6.1 on 2026-08-27 20:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_birthregistration_applicant_age_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='birthregistration',
            options={'ordering': ['-created_at'], 'verbose_name': 'Birth Registration', 'verbose_name_plural': 'Birth Registrations'},
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='applicant_age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(120)], verbose_name='Applicant Age'),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='applicant_name_amharic',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Applicant Name (Amharic)'),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='applicant_name_english',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Applicant Name (English)'),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='applicant_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Applicant Phone'),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='applicant_relation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Applicant Relation'),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='birth_day',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Birth Day'),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='birth_month',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(13)], verbose_name='Birth Month (EC)'),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='birth_year_ec',
            field=models.IntegerField(verbose_name='Birth Year (EC)'),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='birth_year_gc',
            field=models.IntegerField(verbose_name='Birth Year (GC)'),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='child_full_name_amharic',
            field=models.CharField(max_length=200, verbose_name='Child Name (Amharic)'),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='child_full_name_english',
            field=models.CharField(max_length=200, verbose_name='Child Name (English)'),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='child_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/children/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='father_name_amharic',
            field=models.CharField(max_length=200, verbose_name='Father Name (Amharic)'),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='father_name_english',
            field=models.CharField(max_length=200, verbose_name='Father Name (English)'),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='father_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/fathers/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='hospital_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/hospitals/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='hospital_org_name',
            field=models.CharField(max_length=200, verbose_name='Hospital/Organization'),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='mother_name_amharic',
            field=models.CharField(max_length=200, verbose_name='Mother Name (Amharic)'),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='mother_name_english',
            field=models.CharField(max_length=200, verbose_name='Mother Name (English)'),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='mother_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/mothers/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='sex',
            field=models.CharField(choices=[('MALE', 'Male / ወንድ'), ('FEMALE', 'Female / ሴት')], max_length=10, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending / ተጠባባቂ'), ('APPROVED', 'Approved / የፀደቀ'), ('REJECTED', 'Rejected / የተከለከለ')], db_index=True, default='PENDING', max_length=20, verbose_name='Registration Status'),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='subcity',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Subcity'),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='woreda',
            field=models.CharField(max_length=50, verbose_name='Woreda'),
        ),
    ]
