# Generated by Django 6.1 on 2026-08-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_birthregistration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthregistration',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Detailed explanation provided to the applicant if status is REJECTED.', null=True, verbose_name='Rejection Reason'),
        ),
        migrations.AddField(
            model_name='birthregistration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='birthregistration',
            index=models.Index(fields=['status', '-created_at'], name='core_birthr_status_cce3ae_idx'),
        ),
        migrations.AddIndex(
            model_name='birthregistration',
            index=models.Index(fields=['subcity', 'woreda'], name='core_birthr_subcity_b07611_idx'),
        ),
    ]
